"""add hermes_score and hermes_verdict columns to pipeline_stages

Revision ID: 28b5a2d57b6a
Revises: c4d5e6f7a8b9
Create Date: 2026-05-06 08:58:37.990531
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '28b5a2d57b6a'
down_revision: Union[str, None] = 'c4d5e6f7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sandbox_rules_role'), table_name='sandbox_rules')
    op.drop_index(op.f('ix_sandbox_rules_role_tool'), table_name='sandbox_rules')
    op.drop_index(op.f('ix_sandbox_rules_tool'), table_name='sandbox_rules')
    op.drop_table('sandbox_rules')
    op.add_column('pipeline_stages', sa.Column('hermes_score', sa.Float(), nullable=True))
    op.add_column('pipeline_stages', sa.Column('hermes_verdict', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_stages', 'hermes_verdict')
    op.drop_column('pipeline_stages', 'hermes_score')
    op.create_table('sandbox_rules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('tool', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('allowed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sandbox_rules_pkey')),
    sa.UniqueConstraint('role', 'tool', name=op.f('uq_sandbox_rules_role_tool'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_sandbox_rules_tool'), 'sandbox_rules', ['tool'], unique=False)
    op.create_index(op.f('ix_sandbox_rules_role_tool'), 'sandbox_rules', ['role', 'tool'], unique=False)
    op.create_index(op.f('ix_sandbox_rules_role'), 'sandbox_rules', ['role'], unique=False)
    # ### end Alembic commands ###
